#!/usr/bin/env python3

from tqdm.contrib.concurrent import thread_map

import sys
import pandas as pd
import os

# first argument should be a text file containing files to check. Such as one generated by:
# find . -type f > filelist.txt
files = list(pd.read_table(sys.argv[1], header=None).iloc[:, 0])

def set_atime(filename):
    stat = os.stat(filename)
    os.utime(filename, (1672484400, 1672484400))

thread_map(set_atime, files, max_workers=32)
